### ISSUE TITLE
Error while starting docker container

### ISSUE THREAD

**Issue by sijomc** [fhirbase/fhirbase-plv8#179]
I am getting an error when starting docker container. Please advise me to solve this issue.

Following is the error:

~/fhirbase# docker run 1bc27da5b3f0
 * Starting PostgreSQL 9.4 database server
   ...done.
Now using node v6.2.0 (npm v3.8.9)

> fhirbase@0.0.1 test /home/fhirbase/fhirbase
> node_modules/mocha/bin/mocha --compilers mocha --compilers coffee:coffee-script/register  --recursive

/home/fhirbase/fhirbase/plpl/node_modules/libpq/index.js:28
    throw err;
    ^

Error: FATAL:  the database system is starting up
FATAL:  the database system is starting up

    at PQ.connectSync (/home/fhirbase/fhirbase/plpl/node_modules/libpq/index.js:26:15)
    at Client.connectSync (/home/fhirbase/fhirbase/plpl/node_modules/pg-native/index.js:51:11)
    at Object.<anonymous> (/home/fhirbase/fhirbase/plpl/src/plv8.coffee:13:8)
    at Object.<anonymous> (/home/fhirbase/fhirbase/plpl/src/plv8.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fhirbase/fhirbase/test/benchmark_spec.coffee:1:8)
    at Object.<anonymous> (/home/fhirbase/fhirbase/test/benchmark_spec.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/home/fhirbase/fhirbase/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by sijomc** [comment]
Copied  Dockerfile-pg-9.4-plv8-1.4.4 to Dockerfile and build docker
OS Ubuntu 16.04

**Comment by nathando** [comment]
@sijomc Hi, did you manage to resolve the issue ? I encountered similar issue though it's with another node module

```
> fhirbase@0.0.1 test /home/fhirbase/fhirbase
> node_modules/mocha/bin/mocha --compilers mocha --compilers coffee:coffee-script/register  --recursive

module.js:442
    throw err;
    ^

Error: Cannot find module '../../node_modules/fast-json-patch/src/json-patch.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fhirbase/fhirbase/src/fhir/crud.coffee:12:13)
    at Object.<anonymous> (/home/fhirbase/fhirbase/src/fhir/crud.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fhirbase/fhirbase/test/core/schema_spec.coffee:4:8)
    at Object.<anonymous> (/home/fhirbase/fhirbase/test/core/schema_spec.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/fhirbase/fhirbase/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Comment by maksym** [comment]
try now

**Comment by nathando** [comment]
thanks @maksym! It passed that error but got in another one 
```
fhirbase | > fhirbase@0.0.1 test /home/fhirbase/fhirbase
fhirbase | > node_modules/mocha/bin/mocha --compilers mocha --compilers coffee:coffee-script/register  --recursive
fhirbase | 
fhirbase | Error: MetaIndex: Param does not have xpath DomainResource-_text
fhirbase |     at Object.module.exports.parameter (/home/fhirbase/fhirbase/src/fhir/meta_index.coffee:112:11)
fhirbase |     at /home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:14:11
fhirbase |     at Array.forEach (native)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:10:10)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:1:1)
fhirbase |     at Module._compile (module.js:541:32)
fhirbase |     at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
fhirbase |     at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
fhirbase |     at tryModuleLoad (module.js:417:12)
fhirbase |     at Function.Module._load (module.js:409:3)
fhirbase |     at Module.require (module.js:468:17)
fhirbase |     at require (internal/module.js:20:19)
fhirbase |     at /home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:230:27
fhirbase |     at Array.forEach (native)
fhirbase |     at Mocha.loadFiles (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:227:14)
fhirbase |     at Mocha.run (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:495:10)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/node_modules/mocha/bin/_mocha:469:18)
fhirbase |     at Module._compile (module.js:541:32)
fhirbase |     at Object.Module._extensions..js (module.js:550:10)
fhirbase |     at Module.load (module.js:458:32)
fhirbase |     at tryModuleLoad (module.js:417:12)
fhirbase |     at Function.Module._load (module.js:409:3)
fhirbase |     at Function.Module.runMain (module.js:575:10)
fhirbase |     at startup (node.js:160:18)
fhirbase |     at node.js:449:3
fhirbase | 
fhirbase | Error: MetaIndex: Param does not have xpath Resource-_content
fhirbase |     at Object.module.exports.parameter (/home/fhirbase/fhirbase/src/fhir/meta_index.coffee:112:11)
fhirbase |     at /home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:14:11
fhirbase |     at Array.forEach (native)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:10:10)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/test/fhir/meta_index_generative_spec.coffee:1:1)
fhirbase |     at Module._compile (module.js:541:32)
fhirbase |     at Object.loadFile (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
fhirbase |     at Module.load (/home/fhirbase/fhirbase/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
fhirbase |     at tryModuleLoad (module.js:417:12)
fhirbase |     at Function.Module._load (module.js:409:3)
fhirbase |     at Module.require (module.js:468:17)
fhirbase |     at require (internal/module.js:20:19)
fhirbase |     at /home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:230:27
fhirbase |     at Array.forEach (native)
fhirbase |     at Mocha.loadFiles (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:227:14)
fhirbase |     at Mocha.run (/home/fhirbase/fhirbase/node_modules/mocha/lib/mocha.js:495:10)
fhirbase |     at Object.<anonymous> (/home/fhirbase/fhirbase/node_modules/mocha/bin/_mocha:469:18)
fhirbase |     at Module._compile (module.js:541:32)
fhirbase |     at Object.Module._extensions..js (module.js:550:10)
fhirbase |     at Module.load (module.js:458:32)
fhirbase |     at tryModuleLoad (module.js:417:12)
fhirbase |     at Function.Module._load (module.js:409:3)
fhirbase |     at Function.Module.runMain (module.js:575:10)
fhirbase |     at startup (node.js:160:18)
fhirbase |     at node.js:449:3

```

**Comment by nathando** [comment]
the tutorial here is quite recently updated but it is still not working. Is this for the older version of fhirbase ? https://fhirbase.gitbook.io/project/tutorials-1/getting-started
